# Generated by Django 4.0.6 on 2022-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('대여 종료', '대여 종료'), ('대여 가능', '대여 가능'), ('예약 중', '예약 중'), ('대여 중', '대여 중')], max_length=10, verbose_name='상태'),
        ),
    ]
