# Generated by Django 4.0.6 on 2022-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.FileField(null=True, upload_to='develop/', verbose_name='이미지'),
        ),
    ]
