# Generated by Django 4.0.6 on 2022-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('시간', '시간'), ('일', '일'), ('월', '월')], max_length=5, null=True, verbose_name='시간 단위'),
        ),
    ]
