# Generated by Django 4.0.6 on 2022-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_images_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='../static/profile.jpg', upload_to='item/'),
        ),
    ]
