# Generated by Django 4.0.6 on 2022-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_price_alter_item_time_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='../static/default_item.jpg', upload_to='item/'),
        ),
    ]
