# Generated by Django 4.0.6 on 2022-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('borrow', '빌려요'), ('lend', '빌려드려요')], max_length=10, verbose_name='섹션'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '거래 종료'), (1, '거래 가능'), (2, '예약 중'), (3, '거래 중')], verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_unit',
            field=models.CharField(choices=[('hour', '시간'), ('day', '일'), ('month', '월')], max_length=5, null=True, verbose_name='시간 단위'),
        ),
    ]
