# Generated by Django 4.0.6 on 2022-07-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_status_alter_itemimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
