# Generated by Django 4.0.6 on 2022-07-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '거래 종료'), (1, '거래 가능'), (2, '예약 중'), (3, '거래 중')], verbose_name='상태'),
        ),
    ]
