# Generated by Django 4.0.6 on 2022-07-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_delete_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=25, verbose_name='제목'),
        ),
    ]
