# Generated by Django 4.0.6 on 2022-07-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_content_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='가격'),
        ),
    ]
