# Generated by Django 4.0.6 on 2022-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('borrow', '빌려요'), ('lend', '빌려드려요')], max_length=10, verbose_name='섹션'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_unit',
            field=models.CharField(choices=[('hour', '시간'), ('day', '일'), ('month', '월')], max_length=5, null=True, verbose_name='시간 단위'),
        ),
    ]
