# Generated by Django 4.0.6 on 2022-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_section_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('빌려요', '빌려요'), ('빌려드려요', '빌려드려요')], max_length=10, verbose_name='섹션'),
        ),
    ]
