# Generated by Django 4.0.6 on 2022-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.PositiveIntegerField(choices=[('거래 종료', '거래 종료'), ('거래 가능', '거래 가능'), ('예약 중', '예약 중'), ('거래 중', '거래 중')], verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_unit',
            field=models.CharField(choices=[('시간', '시간'), ('일', '일'), ('월', '월')], max_length=5, null=True, verbose_name='시간 단위'),
        ),
    ]
