# Generated by Django 4.0.6 on 2022-08-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
