# Generated by Django 4.0.6 on 2022-08-11 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0008_alter_item_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('판매 금지 물품이에요', '판매 금지 물품이에요'), ('중고거래 게시글이 아니에요', '중고거래 게시글이 아니에요'), ('전문 판매업자 같아요', '전문 판매업자 같아요'), ('사기 글이에요', '사기 글이에요'), ('기타', '기타')], max_length=20, verbose_name='신고 카테고리')),
                ('content', models.TextField(blank=True, max_length=512, verbose_name='신고 내용')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='제목')),
                ('content', models.TextField(max_length=512, verbose_name='피드백 내용')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
    ]
