# Generated by Django 4.0.6 on 2022-08-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_status'),
        ('chat', '0002_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='item',
            field=models.ForeignKey(default='삭제된 물품입니다', on_delete=django.db.models.deletion.SET_DEFAULT, to='item.item'),
        ),
    ]
