# Generated by Django 4.0.6 on 2022-08-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_status'),
        ('chat', '0003_alter_chatroom_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
    ]
