# Generated by Django 4.0.6 on 2022-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('신청 전', '신청 전'), ('검토 중', '검토 중'), ('수락', '수락'), ('거래 종료', '거래 종료')], max_length=6, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=1000, null=True, verbose_name='내용'),
        ),
    ]
