# Generated by Django 4.0.6 on 2022-08-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_status'),
        ('chat', '0005_chatmessage_status_alter_chatmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='status',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='contract_type',
            field=models.CharField(choices=[('신청', '신청'), ('거절', '거절'), ('수락', '수락'), ('종료', '종료')], max_length=6, null=True, verbose_name='신청 유형'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
    ]
