# Generated by Django 4.0.6 on 2022-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_status_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('검토 중', '검토 중'), ('수락', '수락'), ('거절', '거절'), ('거래 종료', '거래 종료')], max_length=6, null=True, verbose_name='상태'),
        ),
    ]
