# Generated by Django 4.0.6 on 2022-07-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_status'),
        ('chat', '0006_alter_chatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
    ]
