# Generated by Django 4.0.6 on 2022-07-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('검토 중', '검토 중'), ('수락', '수락'), ('거절', '거절'), ('대여 종료', '대여 종료')], max_length=6, null=True, verbose_name='상태'),
        ),
    ]
