# Generated by Django 4.0.6 on 2022-07-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatmessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='status',
        ),
    ]
