# Generated by Django 4.0.6 on 2022-07-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../static/default_profile.jpg', upload_to='profile/', verbose_name='이미지'),
        ),
    ]
