# Generated by Django 4.0.6 on 2022-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='develop/', verbose_name='프로필'),
        ),
    ]
