# Generated by Django 4.0.6 on 2022-08-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_reviews_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='유저가 받은 리뷰 갯수'),
        ),
    ]
